### ISSUE TITLE
[PE-D][Tester A] Unable to delete a person with similar name 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-3/tp#113]
![image.png](https://raw.githubusercontent.com/bipbipboopboop/ped/main/files/9b94af08-1d9e-4b8e-9e10-c56bc80dff21.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: bipbipboopboop/ped#3

**Comment by joellow88** [comment]
Bug report shows an irrelevant screenshot. Will retest and fix any bugs in deleteByName if found.
