### ISSUE TITLE
ModCheck has no `back` function

### ISSUE THREAD

**Issue by Acerizm** [AY2223S2-CS2103-F10-3/tp#60]
Currently modcheck will only display contacts that the user wants but cant go back to the previous view

**Comment by joellow88** [comment]
User can use `list` to display all the contacts in ModCheck. Is the functionality of your proposed `back` already achieveable with the current `list`?

**Comment by Acerizm** [comment]
@joellow88 Maybe the user would like to go to the previous view/state after filtering twice ( not sure even filtering twice works as expected ) but this issue is very minor as it is just for improving user experience
